"""
app.py — FinGuard entrypoint

Mounts the frontend (static files + dashboard HTML) onto the FastAPI
backend and serves the whole application from a single process.

Run:
    uvicorn app:app --reload

Then open http://127.0.0.1:8000
API docs (auto-generated by FastAPI): http://127.0.0.1:8000/docs
"""

from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from backend.main import app

app.mount("/static", StaticFiles(directory="frontend/static"), name="static")


@app.get("/")
def serve_dashboard():
    return FileResponse("frontend/templates/index.html")
